name: On Main Commit

on:
  push:
    branches:
      - 'main'

jobs:
  publish-docker-image:
    name: Publish Main Docker Image
    uses: ./.github/workflows/publish-docker-image.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      images: |
        ghcr.io/${{ github.repository }}
