name: On New Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-docker-image:
    uses: ./.github/workflows/publish-docker-image.yaml
    secrets: inherit
    with:
      environment: docker-publish
