name: Pre-Release CI

on:
  push:
    tags:
      - 'v*.*.*-rc.*'

jobs:

  validate:
    name: Validate Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(gh release view ${{ github.ref_name }} --json isPrerelease)

          echo "$response" | jq 

          prerelease=$(echo "$response" | jq -r '.isPrerelease')

          echo "Prerelease: $prerelease"

          if [ "$prerelease" != "true" ]; then
            echo "Tag is not a pre-release"
            exit 1
          fi
        
  publish-docker-image:
    name: Publish Pre-Release Docker Image
    uses: ./.github/workflows/publish-docker-image.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    needs: 
      - validate
    with:
      environment: docker-publish
      images: |
        ${{ github.repository }}
        ghcr.io/${{ github.repository }}
      tags: |
        type=raw,value=${{ github.ref_name }}
