name: Release CI

on:
  push:
    tags:
      # Do not run on pre-release tags
      - '!v*.*.*-rc.*'
      - 'v*.*.*'

jobs:

  publish-docker-image:
    name: Publish Pre-Release Docker Image
    uses: ./.github/workflows/publish-docker-image.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      environment: docker-publish
      images: |
        ${{ github.repository }}
        ghcr.io/${{ github.repository }}
      tags: |
        type=raw,value=${{ github.ref_name }}
        type=raw,value=latest
